---
title: "Exercise Intolerance"
author: "Dylan Armbruster"
date: "2023-01-16"
output: html_document
---

Exercise Intolerance

## R Markdown


```{r}
# Section 1: Setting up the data frames for Breathless

# Start:
# Import the symptomtriggers excel file and load packages, dply, ggplot2
library(dplyr, ggplot)
library(readr)
symptomtriggers <- read_csv("C:/Users/19496/Downloads/symptomtriggers.xlsx - all.csv")



# Step 1: This code creates a sub data frame from symptomstriggers and is
# named Vertigo
Exercise_Intolerance <- data.frame(symptomtriggers$psid2, 
                      symptomtriggers$opensxtrig_exint)

# Step 2: This code renames column symptomtriggers.psid2 to subjects 
Exercise_Intolerance = rename(Exercise_Intolerance, subjects = symptomtriggers.psid2)

# Step 3: This code renames column symptomtrigger.opensxtrig_lhead to 
Exercise_Intolerance = rename(Exercise_Intolerance, subject_triggers = 
                   symptomtriggers.opensxtrig_exint)

# Step 4: These 3 lines of code creates a column called trigger_Period,
# trigger_Relapse, trigger_physicalAcitvity, trigger_Fatigue,           
# trigger_Cognitive, trigger_Stress, trigger_Temperature, trigger_Food, 
# trigger_lackOfSleep.                                                  
Exercise_Intolerance['trigger_Period'] <- NA

Exercise_Intolerance['trigger_Relapse'] <- NA

Exercise_Intolerance['trigger_physicalAcitvity'] <- NA

Exercise_Intolerance['trigger_Fatigue'] <- NA

Exercise_Intolerance['trigger_Cognitive'] <- NA

Exercise_Intolerance['trigger_Stress'] <- NA

Exercise_Intolerance['trigger_Temperature'] <- NA

Exercise_Intolerance['trigger_Food'] <- NA

Exercise_Intolerance['trigger_lackOfSleep'] <- NA

Exercise_Intolerance['trigger_infection'] <- NA


# Step 5: This code searches for strings of symptoms to match to specific coded
# numbers.                                                                     

# Period  
Exercise_Intolerance$trigger_Period[grep("Period|Periods|PMS|ovulation|
                             Menstrual",ignore.case=TRUE
                            ,Exercise_Intolerance$subject_trigger)]<- 1
# COME BACK TO THIS
# Subject 230 mentioned period, but was not referring to the same thing.
# This will be here until I can figure out how to fix the first function to 
# ignore a case like this.
# Subject 189, did not use the word period referring to periods.
Exercise_Intolerance$trigger_Period[grep("a period|long periods",ignore.case=TRUE
                            ,Exercise_Intolerance$subject_trigger)]<- NA

# Relapse 
Exercise_Intolerance$trigger_Relapse[grep("Relapse", ignore.case=TRUE,
                             Exercise_Intolerance$subject_trigger)]<- 1

# Physical Activity 
Exercise_Intolerance$trigger_physicalAcitvity[grep("Exercise|Activity|
                                      active|Exertion|chores
                                      |climbing|overexertion|movement|walking",
                                      ignore.case=TRUE,
                                      Exercise_Intolerance$subject_trigger)]<- 1
# Fatigue
Exercise_Intolerance$trigger_Fatigue[grep("Fatigue|Fatigued|Tiredness", ignore.case=TRUE,
                             Exercise_Intolerance$subject_trigger)]<- 1
# Cognitive
Exercise_Intolerance$trigger_Cognitive[grep("Cognitive" ,ignore.case=TRUE,
                               Exercise_Intolerance$subject_trigger)]<- 1
# Stress
Exercise_Intolerance$trigger_Stress[grep("Stress",ignore.case=TRUE,
                            Exercise_Intolerance$subject_trigger)]<- 1
# Temperature
Exercise_Intolerance$trigger_Temperature[grep("heat|hot|warm|cold" ,
                                 Exercise_Intolerance$subject_trigger)]<- 1
# Food
Exercise_Intolerance$trigger_Food[grep("Food|food|histamine|Eating|diet" , ignore.case=TRUE,
                          Exercise_Intolerance$subject_trigger)]<- 1
# Lack of Sleep
Exercise_Intolerance$trigger_lackOfSleep[grep("sleep",
                                 Exercise_Intolerance$subject_trigger)]<- 1
# Lack of infection
# Note: Subect 192 put "As above" referring to their previous response in 
# fatigue.
Exercise_Intolerance$trigger_infection[grep("infection|As above" ,
                               Exercise_Intolerance$subject_trigger)]<- 1

```

## Including Plots



```{r pressure, echo=FALSE}

```
